# ML - BOOSTING

In [55]:
import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from utils1 import get_classifier_metrics
from sklearn.model_selection import GridSearchCV
from collections import Counter

## Paso 1. Lectura del conjunto de datos procesado

In [2]:
# Cargamos los dataframes 
with open('../data/processed/04_df_invalids_removed.pkl', 'rb') as f:
    df_invalids_removed = pickle.load(f)

with open('../data/processed/04_df_invalids_mode.pkl', 'rb') as f:
    df_invalids_mode = pickle.load(f)

with open('../data/processed/04_df_invalids_knn.pkl', 'rb') as f:
    df_invalids_knn = pickle.load(f)

## Paso 2. Split

In [5]:
X_invalids_removed = df_invalids_removed.drop('Outcome', axis= 1)
y_invalids_removed = df_invalids_removed['Outcome']

X_invalids_mode= df_invalids_mode.drop('Outcome', axis= 1)
y_invalids_mode = df_invalids_mode['Outcome']

X_invalids_knn= df_invalids_knn.drop('Outcome', axis= 1)
y_invalids_knn = df_invalids_knn['Outcome']

X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_invalids_removed, y_invalids_removed, test_size=0.2, random_state=21)
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_invalids_mode, y_invalids_mode, test_size=0.2, random_state=21)
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(X_invalids_knn, y_invalids_knn, test_size=0.2, random_state=21)

## Paso 3. Modelado y Ajuste

In [7]:
model_boosting_default_1 = XGBClassifier(random_state=21)
model_boosting_default_1.fit(X_train_1, y_train_1)

model_boosting_default_2 = XGBClassifier(random_state=21)
model_boosting_default_2.fit(X_train_2, y_train_2)

model_boosting_default_3 = XGBClassifier(random_state=21)
model_boosting_default_3.fit(X_train_3, y_train_3)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

## Paso 4. Predicción

In [9]:
y_pred_test_1 = model_boosting_default_1.predict(X_test_1)
y_pred_train_1 = model_boosting_default_1.predict(X_train_1)

y_pred_test_2 = model_boosting_default_2.predict(X_test_2)
y_pred_train_2 = model_boosting_default_2.predict(X_train_2)

y_pred_test_3 = model_boosting_default_3.predict(X_test_3)
y_pred_train_3 = model_boosting_default_3.predict(X_train_3)

In [12]:
default_model_metrics_1 = get_classifier_metrics(y_pred_test_1, y_test_1, y_pred_train_1, y_train_1, average='weighted')
default_model_metrics_1

           Accuracy  F1 Score  Precision    Recall
Train set  1.000000  1.000000   1.000000  1.000000
Test set   0.734177  0.723725   0.726029  0.734177

In [13]:
default_model_metrics_2 = get_classifier_metrics(y_pred_test_2, y_test_2, y_pred_train_2, y_train_2, average='weighted')
default_model_metrics_2

           Accuracy  F1 Score  Precision    Recall
Train set  1.000000  1.000000   1.000000  1.000000
Test set   0.701299  0.680869   0.699905  0.701299

In [14]:
default_model_metrics_3 = get_classifier_metrics(y_pred_test_3, y_test_3, y_pred_train_3, y_train_3, average='weighted')
default_model_metrics_3

           Accuracy  F1 Score  Precision    Recall
Train set  1.000000  1.000000   1.000000  1.000000
Test set   0.701299  0.685789   0.696685  0.701299

### Modelo optimizado con los hiperparámetros con `GridSearchCV`

In [ ]:
'n_estimators'# número de árboles
    'max_depth' # profundidad máxima de cada árbol
    'learning_rate': # tasa de aprendizaje
    'subsample': # proporción de muestras usadas para entrenar cada árbol
    'colsample_bytree':  # proporción de características usadas por árbol
    'gamma': # regularización: requiere mejora mínima de pérdida para dividir
    'reg_alpha': # L1 regularization (sparse features)
    'reg_lambda': # L2 regularization (default is 1)

In [59]:
# Calcular manualmente el peso para balancear clases (0: no diabetes, 1: diabetes)

counts = Counter(y_train_3)
neg, pos = counts[0], counts[1]

scale_pos_weight_3 = neg / pos

In [60]:
param_grid = {'n_estimators': [20, 30, 40, 50], 
              'max_depth' : [3, 5, 7],
              'learning_rate': [0.01, 0.1, 0.2],          
              'subsample': [0.8, 1.0],                    
              'colsample_bytree': [0.8, 1.0],              
              'gamma': [0, 0.5, 1],
              'scale_pos_weight': [1, scale_pos_weight_3]}  

grid_1 = GridSearchCV(model_boosting_default_1,
                      param_grid,
                      scoring='recall',
                      cv=5)

grid_2 = GridSearchCV(model_boosting_default_2,
                      param_grid,
                      scoring='recall',
                      cv=5)

grid_3 = GridSearchCV(model_boosting_default_3,
                      param_grid,
                      scoring='recall',
                      cv=5)

In [61]:
# Entrenamos el grid con los hiperparametros
grid_1.fit(X_train_1, y_train_1)
#Devuelvemos los mejores parametros despues de entrenarlo
grid_1.best_params_

Exception ignored on calling ctypes callback function: <bound method DataIter._next_wrapper of <xgboost.data.SingleBatchInternalIter object at 0x71d5a5410810>>
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/xgboost/core.py", line 585, in _next_wrapper
    def _next_wrapper(self, this: None) -> int:  # pylint: disable=unused-argument

KeyboardInterrupt:
/home/vscode/.local/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:516: FitFailedWarning:
1 fits failed out of a total of 4320.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/vscode/.local/lib/python3.11/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/xgboost/sklearn.py", line 1663, in fit
    train_dmatrix, evals = _wrap_evaluation_matrices(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/xgboost/sklearn.py", line 628, in _wrap_evaluation_matrices
    train_dmatrix = create_dmatrix(
                    ^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/xgboost/sklearn.py", line 1137, in _create_dmatrix
    return QuantileDMatrix(
           ^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/xgboost/core.py", line 1614, in __init__
    self._init(
  File "/home/vscode/.local/lib/python3.11/site-packages/xgboost/core.py", line 1680, in _init
    _check_call(ret)
  File "/home/vscode/.local/lib/python3.11/site-packages/xgboost/core.py", line 310, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [10:08:35] /workspace/src/common/quantile.h:770: Check failed: count <= total_entries (251 vs. 0) :
Stack trace:
  [bt] (0) /home/vscode/.local/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(+0x2a6ecc) [0x71d5a7210ecc]
  [bt] (1) /home/vscode/.local/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(+0x3ef69c) [0x71d5a735969c]
  [bt] (2) /home/vscode/.local/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(+0x3efaee) [0x71d5a7359aee]
  [bt] (3) /home/vscode/.local/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(+0x5fba94) [0x71d5a7565a94]
  [bt] (4) /home/vscode/.local/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(+0x5e71e0) [0x71d5a75511e0]
  [bt] (5) /home/vscode/.local/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(+0x5ea949) [0x71d5a7554949]
  [bt] (6) /home/vscode/.local/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(+0x57b541) [0x71d5a74e5541]
  [bt] (7) /home/vscode/.local/lib/python3.11/site-packages/xgboost/lib/libxgboost.so(XGQuantileDMatrixCreateFromCallback+0x178) [0x71d5a71233c8]
  [bt] (8) /usr/lib/x86_64-linux-gnu/libffi.so.7(+0x6d1d) [0x71d5f8076d1d]



  warnings.warn(some_fits_failed_message, FitFailedWarning)
/home/vscode/.local/lib/python3.11/site-packages/sklearn/model_selection/_search.py:1135: UserWarning: One or more of the test scores are non-finite: [0.         0.         0.65761905 0.69619048 0.         0.
 0.68666667 0.7652381  0.         0.01       0.70619048 0.7847619
 0.07857143 0.12761905 0.70619048 0.7847619  0.         0.
 0.60714286 0.66714286 0.         0.         0.65666667 0.71714286
 0.01       0.02       0.70571429 0.74619048 0.07809524 0.14714286
 0.70571429 0.74666667 0.         0.         0.61666667 0.63761905
 0.         0.         0.63619048 0.68714286 0.01       0.03
 0.65619048 0.71619048 0.08809524 0.11761905 0.67571429 0.71619048
 0.53857143 0.51857143 0.69571429 0.7647619  0.58761905 0.57809524
 0.70571429 0.74428571 0.58761905 0.57904762 0.68619048 0.7352381
 0.62666667 0.55904762 0.69571429 0.7452381  0.58809524 0.56857143
 0.6852381  0.7547619  0.60761905 0.58809524 0.68571429 0.73571429
 0.63761905 0.60809524 0.65666667 0.71571429 0.59857143 0.59809524
 0.64714286 0.67666667        nan 0.55       0.67571429 0.68619048
 0.57761905 0.59904762 0.63761905 0.66666667 0.59761905 0.57952381
 0.63761905 0.67666667 0.59809524 0.59952381 0.63761905 0.66761905
 0.56761905 0.59761905 0.67666667 0.7552381  0.57714286 0.60761905
 0.69571429 0.71571429 0.57761905 0.58809524 0.68571429 0.70666667
 0.57761905 0.57809524 0.66666667 0.67666667 0.57809524 0.58809524
 0.66571429 0.69666667 0.59714286 0.60904762 0.65571429 0.66714286
 0.60761905 0.59904762 0.65714286 0.65809524 0.59714286 0.58904762
 0.63619048 0.64857143 0.56904762 0.61809524 0.63619048 0.65666667
 0.56904762 0.60904762 0.64619048 0.63666667 0.57809524 0.59857143
 0.66619048 0.65619048 0.55809524 0.57904762 0.64619048 0.64666667
 0.         0.         0.65761905 0.69619048 0.         0.
 0.68666667 0.7652381  0.         0.         0.70619048 0.7847619
 0.06904762 0.13714286 0.70619048 0.7847619  0.         0.
 0.60714286 0.66714286 0.         0.         0.64666667 0.67714286
 0.01       0.01       0.70571429 0.73571429 0.09761905 0.13714286
 0.70571429 0.71619048 0.         0.         0.61666667 0.66666667
 0.         0.         0.63666667 0.70666667 0.01       0.01
 0.68571429 0.70619048 0.08809524 0.13714286 0.70571429 0.69666667
 0.54857143 0.52857143 0.7052381  0.7647619  0.57809524 0.55904762
 0.70571429 0.75428571 0.59761905 0.54857143 0.69571429 0.71571429
 0.59761905 0.54857143 0.68619048 0.71571429 0.56857143 0.57761905
 0.68571429 0.71571429 0.57809524 0.60714286 0.65619048 0.71571429
 0.61809524 0.59809524 0.65666667 0.70619048 0.62761905 0.60809524
 0.62761905 0.69619048 0.56809524 0.52952381 0.6852381  0.70571429
 0.60714286 0.56904762 0.64666667 0.68666667 0.61714286 0.58857143
 0.65714286 0.67714286 0.63714286 0.60857143 0.64666667 0.68714286
 0.57761905 0.58809524 0.69571429 0.7552381  0.56761905 0.59809524
 0.72428571 0.69571429 0.57761905 0.58809524 0.68571429 0.64666667
 0.56809524 0.58809524 0.6847619  0.65666667 0.60714286 0.61809524
 0.6652381  0.71619048 0.61761905 0.60857143 0.6552381  0.66761905
 0.56809524 0.60857143 0.61666667 0.66761905 0.54857143 0.60857143
 0.64666667 0.67761905 0.61761905 0.58857143 0.6952381  0.66761905
 0.64714286 0.59857143 0.67619048 0.65714286 0.64761905 0.59857143
 0.65666667 0.65714286 0.62714286 0.59857143 0.64761905 0.65714286
 0.         0.         0.65761905 0.69619048 0.         0.
 0.68666667 0.7652381  0.         0.         0.70619048 0.7847619
 0.07904762 0.14619048 0.70619048 0.7847619  0.         0.
 0.61714286 0.67714286 0.         0.         0.65666667 0.68714286
 0.         0.00952381 0.70571429 0.73571429 0.07809524 0.16619048
 0.70571429 0.74571429 0.         0.         0.62666667 0.65714286
 0.         0.         0.63666667 0.68666667 0.         0.01
 0.68571429 0.71571429 0.09761905 0.14714286 0.69571429 0.70619048
 0.54857143 0.53904762 0.68619048 0.77428571 0.60714286 0.55904762
 0.7052381  0.79380952 0.62666667 0.57857143 0.7052381  0.78428571
 0.61714286 0.57809524 0.7052381  0.7347619  0.54857143 0.60714286
 0.7052381  0.7452381  0.60761905 0.61714286 0.7052381  0.71571429
 0.61761905 0.61714286 0.68619048 0.71619048 0.61761905 0.61714286
 0.65761905 0.71619048 0.53809524 0.54904762 0.6947619  0.7452381
 0.59666667 0.56904762 0.6752381  0.70619048 0.61666667 0.59857143
 0.67571429 0.69666667 0.60714286 0.59857143 0.66571429 0.68666667
 0.56809524 0.58809524 0.6952381  0.7547619  0.58809524 0.57761905
 0.6852381  0.7352381  0.57761905 0.57761905 0.65619048 0.72571429
 0.56809524 0.57761905 0.66619048 0.72571429 0.58809524 0.61761905
 0.6947619  0.70619048 0.60809524 0.61761905 0.70428571 0.70619048
 0.60809524 0.61761905 0.7047619  0.70619048 0.61761905 0.61761905
 0.7047619  0.70619048 0.54809524 0.60761905 0.65619048 0.69571429
 0.58666667 0.60761905 0.6652381  0.67619048 0.54761905 0.60761905
 0.64571429 0.67619048 0.57761905 0.60761905 0.65571429 0.67619048
 0.         0.         0.70619048 0.80428571 0.         0.
 0.73571429 0.80428571 0.01       0.10761905 0.73571429 0.80428571
 0.14619048 0.2252381  0.7552381  0.79428571 0.         0.
 0.67619048 0.70714286 0.         0.         0.70619048 0.73666667
 0.01       0.17571429 0.71619048 0.74666667 0.1752381  0.27428571
 0.72619048 0.73714286 0.         0.         0.63619048 0.66714286
 0.         0.         0.67571429 0.69761905 0.01       0.16571429
 0.68619048 0.69714286 0.1847619  0.29380952 0.69571429 0.70666667
 0.56761905 0.56857143 0.77380952 0.76428571 0.57714286 0.57809524
 0.73380952 0.77380952 0.58761905 0.58809524 0.7152381  0.77428571
 0.58761905 0.57809524 0.7152381  0.7347619  0.56809524 0.57904762
 0.7347619  0.7552381  0.56809524 0.58857143 0.67619048 0.73619048
 0.58809524 0.61809524 0.68666667 0.68666667 0.59809524 0.61809524
 0.66666667 0.67714286 0.57761905 0.60857143 0.74428571 0.72619048
 0.57809524 0.63809524 0.68666667 0.71571429 0.60809524 0.63857143
 0.68666667 0.70619048 0.58857143 0.61904762 0.67666667 0.69666667
 0.61666667 0.61761905 0.72428571 0.7452381  0.61666667 0.59809524
 0.73380952 0.72571429 0.61666667 0.58809524 0.70428571 0.69571429
 0.61619048 0.57857143 0.6947619  0.65714286 0.59761905 0.61857143
 0.70571429 0.68666667 0.63619048 0.59904762 0.67666667 0.65714286
 0.60714286 0.59857143 0.66666667 0.64761905 0.60714286 0.59857143
 0.65761905 0.61809524 0.61714286 0.59809524 0.66666667 0.72571429
 0.59809524 0.60809524 0.65714286 0.68714286 0.61809524 0.60809524
 0.63761905 0.66714286 0.60809524 0.59809524 0.61761905 0.66714286
 0.         0.         0.70619048 0.80428571 0.         0.
 0.73571429 0.80428571 0.01       0.07761905 0.73571429 0.80428571
 0.1652381  0.2352381  0.7552381  0.79428571 0.         0.
 0.67619048 0.70714286 0.         0.         0.70619048 0.73666667
 0.01       0.14571429 0.71619048 0.74666667 0.1847619  0.27428571
 0.72619048 0.73666667 0.         0.         0.63619048 0.66714286
 0.         0.         0.67619048 0.68761905 0.01       0.14571429
 0.69619048 0.69714286 0.1847619  0.30380952 0.70619048 0.70666667
 0.56761905 0.56857143 0.76380952 0.76428571 0.58714286 0.57809524
 0.73380952 0.77428571 0.57809524 0.58809524 0.7052381  0.77428571
 0.57809524 0.58809524 0.69571429 0.7452381  0.58761905 0.61857143
 0.7252381  0.73571429 0.58714286 0.60857143 0.68619048 0.7452381
 0.62714286 0.61857143 0.67666667 0.69666667 0.61761905 0.60857143
 0.67666667 0.68666667 0.59761905 0.61761905 0.68571429 0.71619048
 0.60761905 0.60904762 0.69571429 0.71571429 0.59857143 0.59904762
 0.67619048 0.71619048 0.60809524 0.60857143 0.68571429 0.68666667
 0.62666667 0.59761905 0.74380952 0.7452381  0.63666667 0.58857143
 0.72428571 0.72571429 0.61714286 0.59761905 0.6852381  0.70666667
 0.59714286 0.59761905 0.63714286 0.68714286 0.62761905 0.60809524
 0.67619048 0.67666667 0.63714286 0.59857143 0.67619048 0.63809524
 0.62714286 0.59857143 0.66619048 0.63809524 0.62714286 0.59857143
 0.66666667 0.63809524 0.60761905 0.60857143 0.64761905 0.71666667
 0.61714286 0.60857143 0.65714286 0.70666667 0.61761905 0.60857143
 0.65666667 0.70666667 0.59761905 0.60857143 0.63714286 0.70666667
 0.         0.         0.70619048 0.80428571 0.         0.
 0.73571429 0.80428571 0.02       0.03       0.73571429 0.80428571
 0.1752381  0.2352381  0.7552381  0.80428571 0.         0.
 0.68619048 0.70714286 0.         0.         0.71619048 0.73666667
 0.02       0.07809524 0.71619048 0.73666667 0.1852381  0.2647619
 0.72619048 0.74666667 0.         0.         0.65619048 0.66714286
 0.         0.         0.66619048 0.69714286 0.02       0.07809524
 0.70619048 0.71714286 0.2047619  0.29428571 0.71619048 0.70714286
 0.55761905 0.57761905 0.76380952 0.76428571 0.57714286 0.59761905
 0.72428571 0.77428571 0.57761905 0.58809524 0.69571429 0.7552381
 0.58714286 0.57809524 0.7052381  0.7547619  0.61714286 0.60761905
 0.71571429 0.73571429 0.61714286 0.59761905 0.69619048 0.71619048
 0.60761905 0.60761905 0.67666667 0.71571429 0.59761905 0.60761905
 0.67666667 0.71571429 0.61619048 0.62714286 0.69571429 0.72619048
 0.61666667 0.61809524 0.68619048 0.71666667 0.61714286 0.62809524
 0.68619048 0.71666667 0.62666667 0.61809524 0.68619048 0.71666667
 0.61714286 0.59809524 0.73428571 0.7647619  0.63666667 0.57857143
 0.7152381  0.7447619  0.61714286 0.57857143 0.7152381  0.7347619
 0.62666667 0.57857143 0.70619048 0.7347619  0.60809524 0.64809524
 0.69571429 0.67666667 0.60761905 0.64809524 0.68619048 0.67666667
 0.61761905 0.64809524 0.68619048 0.67666667 0.61809524 0.64809524
 0.67666667 0.67666667 0.59761905 0.61761905 0.66666667 0.71666667
 0.61666667 0.61761905 0.67619048 0.71666667 0.60714286 0.61761905
 0.65714286 0.71666667 0.60714286 0.61761905 0.67666667 0.71666667]
  warnings.warn(

{'colsample_bytree': 1.0,
 'gamma': 0,
 'learning_rate': 0.01,
 'max_depth': 3,
 'n_estimators': 20,
 'scale_pos_weight': 1.9519230769230769,
 'subsample': 1.0}

In [45]:
grid_2.fit(X_train_2, y_train_2)
grid_2.best_params_

{'colsample_bytree': 0.8,
 'gamma': 0.5,
 'learning_rate': 0.2,
 'max_depth': 7,
 'n_estimators': 20,
 'subsample': 0.8}

In [ ]:
# Entrenamos el grid con los hiperparametros
grid_3.fit(X_train_3, y_train_3)
#Devuelvemos los mejores parametros despues de entrenarlo
grid_3.best_params_

In [47]:
#Modelos con los mejores parametros
grid_boosting_1 = grid_1.best_estimator_
grid_boosting_2 = grid_2.best_estimator_
grid_boosting_3 = grid_3.best_estimator_

In [48]:
# Repetimos el entrenamiento pero ahora con el grid que tiene los hiperparametros establecidos
grid_boosting_1.fit(X_train_1, y_train_1)
grid_boosting_2.fit(X_train_2, y_train_2)
grid_boosting_3.fit(X_train_3, y_train_3)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=1.0, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=0.5, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=7,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=40,
              n_jobs=None, num_parallel_tree=None, ...)

In [49]:
y_pred_test_1_grid = grid_boosting_1.predict(X_test_1)
y_pred_train_1_grid = grid_boosting_1.predict(X_train_1)

y_pred_test_2_grid = grid_boosting_2.predict(X_test_2)
y_pred_train_2_grid = grid_boosting_2.predict(X_train_2)

y_pred_test_3_grid = grid_boosting_3.predict(X_test_3)
y_pred_train_3_grid = grid_boosting_3.predict(X_train_3)

In [50]:
grid_boosting_model_metrics_1 = get_classifier_metrics(y_pred_test_1_grid, y_test_1, y_pred_train_1_grid, y_train_1, average='weighted')
grid_boosting_model_metrics_1

           Accuracy  F1 Score  Precision    Recall
Train set  0.949045  0.949045   0.949045  0.949045
Test set   0.746835  0.738678   0.739992  0.746835

In [51]:
grid_boosting_model_metrics_2 = get_classifier_metrics(y_pred_test_2_grid, y_test_2, y_pred_train_2_grid, y_train_2, average='weighted')
grid_boosting_model_metrics_2

           Accuracy  F1 Score  Precision    Recall
Train set  0.946254  0.945503   0.947319  0.946254
Test set   0.701299  0.690035   0.695159  0.701299

In [52]:
grid_boosting_model_metrics_3 = get_classifier_metrics(y_pred_test_3_grid, y_test_3, y_pred_train_3_grid, y_train_3, average='weighted')
grid_boosting_model_metrics_3

           Accuracy  F1 Score  Precision    Recall
Train set  0.978827  0.978709   0.979069  0.978827
Test set   0.733766  0.722834   0.731800  0.733766